blogtitle: "It's a Winogradsky Life" # TODO: give your blog a title
baseurl: "/assignment-team-website" # TODO: replace with the name of your team's blog repository
imageurl: "/images" # this is the location of the images
